import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Container from "../components/big/Container/Container";
import Navbar from "../components/big/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Ace:The AI",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} text-text antialiased`}>
				<Navbar />
				<Container>{children}</Container>
			</body>
		</html>
	);
}
